<?php

use Illuminate\Database\Seeder;
use App\BusinessArea;

class BusinessAreaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0111', 'description' => 'Cultivo de cereales (excepto arroz), leguminosas y semillas oleaginosas']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0112', 'description' => 'Cultivo de arroz']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0113', 'description' => 'Cultivo de hortalizas, raíces y tubérculos']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0114', 'description' => 'Cultivo de caña de azúcar']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0115', 'description' => 'Cultivo de tabaco']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0116', 'description' => 'Cultivo de plantas para fibras textiles']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0119', 'description' => 'Otros cultivos no perennes']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0121', 'description' => 'Cultivo de la vid']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0122', 'description' => 'Cultivo de frutos tropicales y subtropicales']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0123', 'description' => 'Cultivo de cítricos']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0124', 'description' => 'Cultivo de frutos con hueso y pepitas']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0125', 'description' => 'Cultivo de otros árboles y arbustos frutales y frutos secos']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0126', 'description' => 'Cultivo de frutos oleaginosos']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0127', 'description' => 'Cultivo de plantas para bebidas']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0128', 'description' => 'Cultivo de especias, plantas aromáticas, medicinales y farmacéuticas']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0129', 'description' => 'Otros cultivos perennes']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0130', 'description' => 'Propagación de plantas']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0141', 'description' => 'Explotación de ganado bovino para la producción de leche']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0142', 'description' => 'Explotación de otro ganado bovino y búfalos']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0143', 'description' => 'Explotación de caballos y otros equinos']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0144', 'description' => 'Explotación de camellos y otros camélidos']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0145', 'description' => 'Explotación de ganado ovino y caprino']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0146', 'description' => 'Explotación de ganado porcino']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0147', 'description' => 'Avicultura']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0149', 'description' => 'Otras explotaciones de ganado']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0150', 'description' => 'Producción agrícola combinada con la producción ganadera']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0161', 'description' => 'Actividades de apoyo a la agricultura']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0162', 'description' => 'Actividades de apoyo a la ganadería']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0163', 'description' => 'Actividades de preparación posterior a la cosecha']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0164', 'description' => 'Tratamiento de semillas para reproducción']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0170', 'description' => 'Caza, captura de animales y servicios relacionados con las mismas']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0210', 'description' => 'Silvicultura y otras actividades forestales']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0220', 'description' => 'Explotación de la madera']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0230', 'description' => 'Recolección de productos silvestres, excepto madera']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0240', 'description' => 'Servicios de apoyo a la silvicultura']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0311', 'description' => 'Pesca marina']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0312', 'description' => 'Pesca en agua dulce']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0321', 'description' => 'Acuicultura marina']);
        BusinessArea::create(['area_group_id' => '1', 'area_code' => '0322', 'description' => 'Acuicultura en agua dulce']);
        /* 2 */
        BusinessArea::create(['area_group_id' => '2', 'area_code' => '0510', 'description' => 'Extracción de antracita y hulla']);
        BusinessArea::create(['area_group_id' => '2', 'area_code' => '0520', 'description' => 'Extracción de lignito']);
        BusinessArea::create(['area_group_id' => '2', 'area_code' => '0610', 'description' => 'Extracción de crudo de petróleo']);
        BusinessArea::create(['area_group_id' => '2', 'area_code' => '0620', 'description' => 'Extracción de gas natural']);
        BusinessArea::create(['area_group_id' => '2', 'area_code' => '0710', 'description' => 'Extracción de minerales de hierro']);
        BusinessArea::create(['area_group_id' => '2', 'area_code' => '0721', 'description' => 'Extracción de minerales de uranio y torio']);
        BusinessArea::create(['area_group_id' => '2', 'area_code' => '0729', 'description' => 'Extracción de otros minerales metálicos no férreos']);
        BusinessArea::create(['area_group_id' => '2', 'area_code' => '0811', 'description' => 'Extracción de piedra ornamental y para la construcción, piedra caliza, yeso, creta y pizarra']);
        BusinessArea::create(['area_group_id' => '2', 'area_code' => '0812', 'description' => 'Extracción de gravas y arenas']);
        BusinessArea::create(['area_group_id' => '2', 'area_code' => '0891', 'description' => 'Extracción de minerales para productos químicos y fertilizantes']);
        BusinessArea::create(['area_group_id' => '2', 'area_code' => '0892', 'description' => 'Extracción de turba']);
        BusinessArea::create(['area_group_id' => '2', 'area_code' => '0893', 'description' => 'Extracción de sal']);
        BusinessArea::create(['area_group_id' => '2', 'area_code' => '0899', 'description' => 'Otras industrias extractivas n.c.o.p.']);
        BusinessArea::create(['area_group_id' => '2', 'area_code' => '0910', 'description' => 'Actividades de apoyo a la extracción de petróleo y gas natural']);
        BusinessArea::create(['area_group_id' => '2', 'area_code' => '0990', 'description' => 'Actividades de apoyo a otras industrias extractivas']);
        /* 3 */
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1011', 'description' => 'Procesado y conservación de carne']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1012', 'description' => 'Procesado y conservación de volatería']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1013', 'description' => 'Elaboración de productos cárnicos y de volatería']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1021', 'description' => 'Procesado de pescados, crustáceos y moluscos']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1022', 'description' => 'Fabricación de conservas de pescado']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1031', 'description' => 'Procesado y conservación de patatas']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1032', 'description' => 'Elaboración de zumos de frutas y hortalizas']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1039', 'description' => 'Otro procesado y conservación de frutas y hortalizas']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1042', 'description' => 'Fabricación de margarina y grasas comestibles similares']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1043', 'description' => 'Fabricación de aceite de oliva']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1044', 'description' => 'Fabricación de otros aceites y grasas']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1052', 'description' => 'Elaboración de helados']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1053', 'description' => 'Fabricación de quesos']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1054', 'description' => 'Preparación de leche y otros productos lácteos']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1061', 'description' => 'Fabricación de productos de molinería']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1062', 'description' => 'Fabricación de almidones y productos amiláceos']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1071', 'description' => 'Fabricación de pan y de productos frescos de panadería y pastelería']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1072', 'description' => 'Fabricación de galletas y productos de panadería y pastelería de larga duración']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1073', 'description' => 'Fabricación de pastas alimenticias, cuscús y productos similares']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1081', 'description' => 'Fabricación de azúcar']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1082', 'description' => 'Fabricación de cacao, chocolate y productos de confitería']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1083', 'description' => 'Elaboración de café, té e infusiones']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1084', 'description' => 'Elaboración de especias, salsas y condimentos']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1085', 'description' => 'Elaboración de platos y comidas preparados']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1086', 'description' => 'Elaboración de preparados alimenticios homogeneizados y alimentos dietéticos']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1089', 'description' => 'Elaboración de otros productos alimenticios n.c.o.p.']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1091', 'description' => 'Fabricación de productos para la alimentación de animales de granja']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1092', 'description' => 'Fabricación de productos para la alimentación de animales de compañía']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1101', 'description' => 'Destilación, rectificación y mezcla de bebidas alcohólicas']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1102', 'description' => 'Elaboración de vinos']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1103', 'description' => 'Elaboración de sidra y otras bebidas fermentadas a partir de frutas']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1104', 'description' => 'Elaboración de otras bebidas no destiladas, procedentes de la fermentación']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1105', 'description' => 'Fabricación de cerveza']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1106', 'description' => 'Fabricación de malta']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1107', 'description' => 'Fabricación de bebidas no alcohólicas']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1200', 'description' => 'Industria del tabaco']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1310', 'description' => 'Preparación e hilado de fibras textiles']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1320', 'description' => 'Fabricación de tejidos textiles']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1330', 'description' => 'Acabado de textiles']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1391', 'description' => 'Fabricación de tejidos de punto']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1392', 'description' => 'Fabricación de artículos confeccionados con textiles, excepto prendas de vestir']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1393', 'description' => 'Fabricación de alfombras y moquetas']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1394', 'description' => 'Fabricación de cuerdas, cordeles, bramantes y redes']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1395', 'description' => 'Fabricación de telas no tejidas y artículos confeccionados con ellas, excepto prendas de vestir']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1396', 'description' => 'Fabricación de otros productos textiles de uso técnico e industrial']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1399', 'description' => 'Fabricación de otros productos textiles n.c.o.p.']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1411', 'description' => 'Confección de prendas de vestir de cuero']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1412', 'description' => 'Confección de ropa de trabajo']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1413', 'description' => 'Confección de otras prendas de vestir exteriores']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1414', 'description' => 'Confección de ropa interior']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1419', 'description' => 'Confección de otras prendas de vestir y accesorios']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1420', 'description' => 'Fabricación de artículos de peletería']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1431', 'description' => 'Confección de calcetería']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1439', 'description' => 'Confección de otras prendas de vestir de punto']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1511', 'description' => 'Preparación, curtido y acabado del cuero']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1512', 'description' => 'Fabricación de artículos de marroquinería, viaje y de guarnicionería y talabartería']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1520', 'description' => 'Fabricación de calzado']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1610', 'description' => 'Aserrado y cepillado de la madera']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1621', 'description' => 'Fabricación de chapas y tableros de madera']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1622', 'description' => 'Fabricación de suelos de madera ensamblados']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1623', 'description' => 'Fabricación de otras estructuras de madera y piezas de carpintería y ebanistería para la construcción']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1624', 'description' => 'Fabricación de envases y embalajes de madera']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1629', 'description' => 'Fabricación de otros productos de madera']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1711', 'description' => 'Fabricación de pasta papelera']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1712', 'description' => 'Fabricación de papel y cartón']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1721', 'description' => 'Fabricación de papel y cartón ondulados']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1722', 'description' => 'Fabricación de artículos de papel y cartón para uso doméstico, sanitario e higiénico']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1723', 'description' => 'Fabricación de artículos de papelería']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1724', 'description' => 'Fabricación de papeles pintados']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1729', 'description' => 'Fabricación de otros artículos de papel y cartón']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1811', 'description' => 'Artes gráficas y servicios relacionados con las mismas']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1812', 'description' => 'Otras actividades de impresión y artes gráficas']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1813', 'description' => 'Servicios de preimpresión y preparación de soportes']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1814', 'description' => 'Encuadernación y servicios relacionados con la misma']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1820', 'description' => 'Reproducción de soportes grabados']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1910', 'description' => 'Coquerías']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '1920', 'description' => 'Refino de petróleo']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2011', 'description' => 'Fabricación de gases industriales']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2012', 'description' => 'Fabricación de colorantes y pigmentos']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2013', 'description' => 'Fabricación de otros productos básicos de química inorgánica']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2014', 'description' => 'Fabricación de otros productos básicos de química orgánica']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2015', 'description' => 'Fabricación de fertilizantes y compuestos nitrogenados']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2016', 'description' => 'Fabricación de plásticos en formas primarias']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2017', 'description' => 'Fabricación de caucho sintético en formas primarias']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2020', 'description' => 'Fabricación de pesticidas y otros productos agroquímicos']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2030', 'description' => 'Fabricación de pinturas, barnices y revestimientos similares']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2041', 'description' => 'Fabricación de jabones, detergentes y otros artículos de limpieza y abrillantamiento']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2042', 'description' => 'Fabricación de perfumes y cosméticos']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2051', 'description' => 'Fabricación de explosivos']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2052', 'description' => 'Fabricación de colas']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2053', 'description' => 'Fabricación de aceites esenciales']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2059', 'description' => 'Fabricación de otros productos químicos n.c.o.p.']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2060', 'description' => 'Fabricación de fibras artificiales y sintéticas']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2110', 'description' => 'Fabricación de productos farmacéuticos de base']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2120', 'description' => 'Fabricación de especialidades farmacéuticas']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2211', 'description' => 'Fabricación de neumáticos y cámaras de caucho']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2219', 'description' => 'Fabricación de otros productos de caucho']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2221', 'description' => 'Fabricación de placas, hojas, tubos y perfiles de plástico']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2222', 'description' => 'Fabricación de envases y embalajes de plástico']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2223', 'description' => 'Fabricación de productos de plástico para la construcción']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2229', 'description' => 'Fabricación de otros productos de plástico']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2311', 'description' => 'Fabricación de vidrio plano']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2312', 'description' => 'Manipulado y transformación de vidrio plano']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2313', 'description' => 'Fabricación de vidrio hueco']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2314', 'description' => 'Fabricación de fibra de vidrio']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2319', 'description' => 'Fabricación y manipulado de otro vidrio, incluido el vidrio técnico']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2320', 'description' => 'Fabricación de productos cerámicos refractarios']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2331', 'description' => 'Fabricación de azulejos y baldosas de cerámica']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2332', 'description' => 'Fabricación de ladrillos, tejas y productos de tierras cocidas para la construcción']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2341', 'description' => 'Fabricación de artículos cerámicos de uso doméstico y ornamental']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2342', 'description' => 'Fabricación de aparatos sanitarios cerámicos']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2343', 'description' => 'Fabricación de aisladores y piezas aislantes de material cerámico']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2344', 'description' => 'Fabricación de otros productos cerámicos de uso técnico']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2349', 'description' => 'Fabricación de otros productos cerámicos']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2351', 'description' => 'Fabricación de cemento']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2352', 'description' => 'Fabricación de cal y yeso']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2361', 'description' => 'Fabricación de elementos de hormigón para la construcción']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2362', 'description' => 'Fabricación de elementos de yeso para la construcción']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2363', 'description' => 'Fabricación de hormigón fresco']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2364', 'description' => 'Fabricación de mortero']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2365', 'description' => 'Fabricación de fibrocemento']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2369', 'description' => 'Fabricación de otros productos de hormigón, yeso y cemento']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2370', 'description' => 'Corte, tallado y acabado de la piedra']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2391', 'description' => 'Fabricación de productos abrasivos']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2399', 'description' => 'Fabricación de otros productos minerales no metálicos n.c.o.p.']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2410', 'description' => 'Fabricación de productos básicos de hierro, acero y ferroaleaciones']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2420', 'description' => 'Fabricación de tubos, tuberías, perfiles huecos y sus accesorios, de acero']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2431', 'description' => 'Estirado en frío']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2432', 'description' => 'Laminación en frío']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2433', 'description' => 'Producción de perfiles en frío por conformación con plegado']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2434', 'description' => 'Trefilado en frío']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2441', 'description' => 'Producción de metales preciosos']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2442', 'description' => 'Producción de aluminio']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2443', 'description' => 'Producción de plomo, zinc y estaño']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2444', 'description' => 'Producción de cobre']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2445', 'description' => 'Producción de otros metales no férreos']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2446', 'description' => 'Procesamiento de combustibles nucleares']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2451', 'description' => 'Fundición de hierro']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2452', 'description' => 'Fundición de acero']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2453', 'description' => 'Fundición de metales ligeros']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2454', 'description' => 'Fundición de otros metales no férreos']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2511', 'description' => 'Fabricación de estructuras metálicas y sus componentes']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2512', 'description' => 'Fabricación de carpintería metálica']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2521', 'description' => 'Fabricación de radiadores y calderas para calefacción central']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2529', 'description' => 'Fabricación de otras cisternas, grandes depósitos y contenedores de metal']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2530', 'description' => 'Fabricación de generadores de vapor, excepto calderas de calefacción central']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2540', 'description' => 'Fabricación de armas y municiones']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2550', 'description' => 'Forja, estampación y embutición de metales']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2561', 'description' => 'Tratamiento y revestimiento de metales']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2562', 'description' => 'Ingeniería mecánica por cuenta de terceros']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2571', 'description' => 'Fabricación de artículos de cuchillería y cubertería']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2572', 'description' => 'Fabricación de cerraduras y herrajes']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2573', 'description' => 'Fabricación de herramientas']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2591', 'description' => 'Fabricación de bidones y toneles de hierro o acero']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2592', 'description' => 'Fabricación de envases y embalajes metálicos ligeros']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2593', 'description' => 'Fabricación de productos de alambre, cadenas y muelles']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2594', 'description' => 'Fabricación de pernos y productos de tornillería']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2599', 'description' => 'Fabricación de otros productos metálicos n.c.o.p.']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2611', 'description' => 'Fabricación de componentes electrónicos']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2612', 'description' => 'Fabricación de circuitos impresos ensamblados']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2620', 'description' => 'Fabricación de ordenadores y equipos periféricos']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2630', 'description' => 'Fabricación de equipos de telecomunicaciones']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2640', 'description' => 'Fabricación de productos electrónicos de consumo']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2651', 'description' => 'Fabricación de instrumentos y aparatos de medida, verificación y navegación']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2652', 'description' => 'Fabricación de relojes']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2660', 'description' => 'Fabricación de equipos de radiación, electromédicos y electroterapéuticos']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2670', 'description' => 'Fabricación de instrumentos de óptica y equipo fotográfico']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2680', 'description' => 'Fabricación de soportes magnéticos y ópticos']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2711', 'description' => 'Fabricación de motores, generadores y transformadores eléctricos']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2712', 'description' => 'Fabricación de aparatos de distribución y control eléctrico']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2720', 'description' => 'Fabricación de pilas y acumuladores eléctricos']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2731', 'description' => 'Fabricación de cables de fibra óptica']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2732', 'description' => 'Fabricación de otros hilos y cables electrónicos y eléctricos']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2733', 'description' => 'Fabricación de dispositivos de cableado']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2740', 'description' => 'Fabricación de lámparas y aparatos eléctricos de iluminación']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2751', 'description' => 'Fabricación de electrodomésticos']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2752', 'description' => 'Fabricación de aparatos domésticos no eléctricos']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2790', 'description' => 'Fabricación de otro material y equipo eléctrico']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2811', 'description' => 'Fabricación de motores y turbinas, excepto los destinados a aeronaves, vehículos automóviles y ciclomotores']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2812', 'description' => 'Fabricación de equipos de transmisión hidráulica y neumática']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2813', 'description' => 'Fabricación de otras bombas y compresores']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2814', 'description' => 'Fabricación de otra grifería y válvulas']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2815', 'description' => 'Fabricación de cojinetes, engranajes y órganos mecánicos de transmisión']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2821', 'description' => 'Fabricación de hornos y quemadores']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2822', 'description' => 'Fabricación de maquinaria de elevación y manipulación']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2823', 'description' => 'Fabricación de máquinas y equipos de oficina, excepto equipos informáticos']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2824', 'description' => 'Fabricación de herramientas eléctricas manuales']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2825', 'description' => 'Fabricación de maquinaria de ventilación y refrigeración no doméstica']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2829', 'description' => 'Fabricación de otra maquinaria de uso general n.c.o.p.']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2830', 'description' => 'Fabricación de maquinaria agraria y forestal']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2841', 'description' => 'Fabricación de máquinas herramienta para trabajar el metal']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2849', 'description' => 'Fabricación de otras máquinas herramienta']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2891', 'description' => 'Fabricación de maquinaria para la industria metalúrgica']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2892', 'description' => 'Fabricación de maquinaria para las industrias extractivas y de la construcción']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2893', 'description' => 'Fabricación de maquinaria para la industria de la alimentación, bebidas y tabaco']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2894', 'description' => 'Fabricación de maquinaria para las industrias textil, de la confección y del cuero']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2895', 'description' => 'Fabricación de maquinaria para la industria del papel y del cartón']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2896', 'description' => 'Fabricación de maquinaria para la industria del plástico y el caucho']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2899', 'description' => 'Fabricación de otra maquinaria para usos específicos n.c.o.p.']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2910', 'description' => 'Fabricación de vehículos de motor']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2920', 'description' => 'Fabricación de carrocerías para vehículos de motor']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2931', 'description' => 'Fabricación de equipos eléctricos y electrónicos para vehículos de motor']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '2932', 'description' => 'Fabricación de otros componentes, piezas y accesorios para vehículos de motor']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '3011', 'description' => 'Construcción de barcos y estructuras flotantes']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '3012', 'description' => 'Construcción de embarcaciones de recreo y deporte']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '3020', 'description' => 'Fabricación de locomotoras y material ferroviario']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '3030', 'description' => 'Construcción aeronáutica y espacial y su maquinaria']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '3040', 'description' => 'Fabricación de vehículos militares de combate']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '3091', 'description' => 'Fabricación de motocicletas']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '3092', 'description' => 'Fabricación de bicicletas y de vehículos para personas con discapacidad']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '3099', 'description' => 'Fabricación de otro material de transporte n.c.o.p.']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '3101', 'description' => 'Fabricación de muebles de oficina y de establecimientos comerciales']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '3102', 'description' => 'Fabricación de muebles de cocina']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '3103', 'description' => 'Fabricación de colchones']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '3109', 'description' => 'Fabricación de otros muebles']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '3211', 'description' => 'Fabricación de monedas']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '3212', 'description' => 'Fabricación de artículos de joyería y artículos similares']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '3213', 'description' => 'Fabricación de artículos de bisutería y artículos similares']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '3220', 'description' => 'Fabricación de instrumentos musicales']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '3230', 'description' => 'Fabricación de artículos de deporte']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '3240', 'description' => 'Fabricación de juegos y juguetes']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '3250', 'description' => 'Fabricación de instrumentos y suministros médicos y odontológicos']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '3291', 'description' => 'Fabricación de escobas, brochas y cepillos']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '3299', 'description' => 'Otras industrias manufactureras n.c.o.p.']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '3311', 'description' => 'Reparación de productos metálicos']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '3312', 'description' => 'Reparación de maquinaria']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '3313', 'description' => 'Reparación de equipos electrónicos y ópticos']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '3314', 'description' => 'Reparación de equipos eléctricos']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '3315', 'description' => 'Reparación y mantenimiento naval']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '3316', 'description' => 'Reparación y mantenimiento aeronáutico y espacial']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '3317', 'description' => 'Reparación y mantenimiento de otro material de transporte']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '3319', 'description' => 'Reparación de otros equipos']);
        BusinessArea::create(['area_group_id' => '3', 'area_code' => '3320', 'description' => 'Instalación de máquinas y equipos industriales']);
        /* 4 */
        BusinessArea::create(['area_group_id' => '4', 'area_code' => '3512', 'description' => 'Transporte de energía eléctrica']);
        BusinessArea::create(['area_group_id' => '4', 'area_code' => '3513', 'description' => 'Distribución de energía eléctrica']);
        BusinessArea::create(['area_group_id' => '4', 'area_code' => '3514', 'description' => 'Comercio de energía eléctrica']);
        BusinessArea::create(['area_group_id' => '4', 'area_code' => '3515', 'description' => 'Producción de energía hidroeléctrica']);
        BusinessArea::create(['area_group_id' => '4', 'area_code' => '3516', 'description' => 'Producción de energía eléctrica de origen térmico convencional']);
        BusinessArea::create(['area_group_id' => '4', 'area_code' => '3517', 'description' => 'Producción de energía eléctrica de origen nuclear']);
        BusinessArea::create(['area_group_id' => '4', 'area_code' => '3518', 'description' => 'Producción de energía eléctrica de origen eólico']);
        BusinessArea::create(['area_group_id' => '4', 'area_code' => '3519', 'description' => 'Producción de energía eléctrica de otros tipos']);
        BusinessArea::create(['area_group_id' => '4', 'area_code' => '3521', 'description' => 'Producción de gas']);
        BusinessArea::create(['area_group_id' => '4', 'area_code' => '3522', 'description' => 'Distribución por tubería de combustibles gaseosos']);
        BusinessArea::create(['area_group_id' => '4', 'area_code' => '3523', 'description' => 'Comercio de gas por tubería']);
        BusinessArea::create(['area_group_id' => '4', 'area_code' => '3530', 'description' => 'Suministro de vapor y aire acondicionado']);
        /* 5 */
        BusinessArea::create(['area_group_id' => '5', 'area_code' => '3600', 'description' => 'Captación, depuración y distribución de agua']);
        BusinessArea::create(['area_group_id' => '5', 'area_code' => '3700', 'description' => 'Recogida y tratamiento de aguas residuales']);
        BusinessArea::create(['area_group_id' => '5', 'area_code' => '3811', 'description' => 'Recogida de residuos no peligrosos']);
        BusinessArea::create(['area_group_id' => '5', 'area_code' => '3812', 'description' => 'Recogida de residuos peligrosos']);
        BusinessArea::create(['area_group_id' => '5', 'area_code' => '3821', 'description' => 'Tratamiento y eliminación de residuos no peligrosos']);
        BusinessArea::create(['area_group_id' => '5', 'area_code' => '3822', 'description' => 'Tratamiento y eliminación de residuos peligrosos']);
        BusinessArea::create(['area_group_id' => '5', 'area_code' => '3831', 'description' => 'Separación y clasificación de materiales']);
        BusinessArea::create(['area_group_id' => '5', 'area_code' => '3832', 'description' => 'Valorización de materiales ya clasificados']);
        BusinessArea::create(['area_group_id' => '5', 'area_code' => '3900', 'description' => 'Actividades de descontaminación y otros servicios de gestión de residuos']);
        /* 6 */
        BusinessArea::create(['area_group_id' => '6', 'area_code' => '4110', 'description' => 'Promoción inmobiliaria']);
        BusinessArea::create(['area_group_id' => '6', 'area_code' => '4121', 'description' => 'Construcción de edificios residenciales']);
        BusinessArea::create(['area_group_id' => '6', 'area_code' => '4122', 'description' => 'Construcción de edificios no residenciales']);
        BusinessArea::create(['area_group_id' => '6', 'area_code' => '4211', 'description' => 'Construcción de carreteras y autopistas']);
        BusinessArea::create(['area_group_id' => '6', 'area_code' => '4212', 'description' => 'Construcción de vías férreas de superficie y subterráneas']);
        BusinessArea::create(['area_group_id' => '6', 'area_code' => '4213', 'description' => 'Construcción de puentes y túneles']);
        BusinessArea::create(['area_group_id' => '6', 'area_code' => '4221', 'description' => 'Construcción de redes para fluidos']);
        BusinessArea::create(['area_group_id' => '6', 'area_code' => '4222', 'description' => 'Construcción de redes eléctricas y de telecomunicaciones']);
        BusinessArea::create(['area_group_id' => '6', 'area_code' => '4291', 'description' => 'Obras hidráulicas']);
        BusinessArea::create(['area_group_id' => '6', 'area_code' => '4299', 'description' => 'Construcción de otros proyectos de ingeniería civil n.c.o.p.']);
        BusinessArea::create(['area_group_id' => '6', 'area_code' => '4311', 'description' => 'Demolición']);
        BusinessArea::create(['area_group_id' => '6', 'area_code' => '4312', 'description' => 'Preparación de terrenos']);
        BusinessArea::create(['area_group_id' => '6', 'area_code' => '4313', 'description' => 'Perforaciones y sondeos']);
        BusinessArea::create(['area_group_id' => '6', 'area_code' => '4321', 'description' => 'Instalaciones eléctricas']);
        BusinessArea::create(['area_group_id' => '6', 'area_code' => '4322', 'description' => 'Fontanería, instalaciones de sistemas de calefacción y aire acondicionado']);
        BusinessArea::create(['area_group_id' => '6', 'area_code' => '4329', 'description' => 'Otras instalaciones en obras de construcción']);
        BusinessArea::create(['area_group_id' => '6', 'area_code' => '4331', 'description' => 'Revocamiento']);
        BusinessArea::create(['area_group_id' => '6', 'area_code' => '4332', 'description' => 'Instalación de carpintería']);
        BusinessArea::create(['area_group_id' => '6', 'area_code' => '4333', 'description' => 'Revestimiento de suelos y paredes']);
        BusinessArea::create(['area_group_id' => '6', 'area_code' => '4334', 'description' => 'Pintura y acristalamiento']);
        BusinessArea::create(['area_group_id' => '6', 'area_code' => '4339', 'description' => 'Otro acabado de edificios']);
        BusinessArea::create(['area_group_id' => '6', 'area_code' => '4391', 'description' => 'Construcción de cubiertas']);
        BusinessArea::create(['area_group_id' => '6', 'area_code' => '4399', 'description' => 'Otras actividades de construcción especializada n.c.o.p.']);
        /* 7 */
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4511', 'description' => 'Venta de automóviles y vehículos de motor ligeros']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4519', 'description' => 'Venta de otros vehículos de motor']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4520', 'description' => 'Mantenimiento y reparación de vehículos de motor']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4531', 'description' => 'Comercio al por mayor de repuestos y accesorios de vehículos de motor']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4532', 'description' => 'Comercio al por menor de repuestos y accesorios de vehículos de motor']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4540', 'description' => 'Venta, mantenimiento y reparación de motocicletas y de sus repuestos y accesorios']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4611', 'description' => 'Intermediarios del comercio de materias primas agrarias, animales vivos, materias primas textiles y productos semielaborados']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4612', 'description' => 'Intermediarios del comercio de combustibles, minerales, metales y productos químicos industriales']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4613', 'description' => 'Intermediarios del comercio de la madera y materiales de construcción']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4614', 'description' => 'Intermediarios del comercio de maquinaria, equipo industrial, embarcaciones y aeronaves']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4615', 'description' => 'Intermediarios del comercio de muebles, artículos para el hogar y ferretería']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4616', 'description' => 'Intermediarios del comercio de textiles, prendas de vestir, peletería, calzado y artículos de cuero']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4617', 'description' => 'Intermediarios del comercio de productos alimenticios, bebidas y tabaco']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4618', 'description' => 'Intermediarios del comercio especializados en la venta de otros productos específicos']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4619', 'description' => 'Intermediarios del comercio de productos diversos']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4621', 'description' => 'Comercio al por mayor de cereales, tabaco en rama, simientes y alimentos para animales']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4622', 'description' => 'Comercio al por mayor de flores y plantas']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4623', 'description' => 'Comercio al por mayor de animales vivos']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4624', 'description' => 'Comercio al por mayor de cueros y pieles']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4631', 'description' => 'Comercio al por mayor de frutas y hortalizas']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4632', 'description' => 'Comercio al por mayor de carne y productos cárnicos']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4633', 'description' => 'Comercio al por mayor de productos lácteos, huevos, aceites y grasas comestibles']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4634', 'description' => 'Comercio al por mayor de bebidas']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4635', 'description' => 'Comercio al por mayor de productos del tabaco']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4636', 'description' => 'Comercio al por mayor de azúcar, chocolate y confitería']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4637', 'description' => 'Comercio al por mayor de café, té, cacao y especias']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4638', 'description' => 'Comercio al por mayor de pescados y mariscos y otros productos alimenticios']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4639', 'description' => 'Comercio al por mayor, no especializado, de productos alimenticios, bebidas y tabaco']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4641', 'description' => 'Comercio al por mayor de textiles']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4642', 'description' => 'Comercio al por mayor de prendas de vestir y calzado']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4643', 'description' => 'Comercio al por mayor de aparatos electrodomésticos']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4644', 'description' => 'Comercio al por mayor de porcelana, cristalería y artículos de limpieza']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4645', 'description' => 'Comercio al por mayor de productos perfumería y cosmética']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4646', 'description' => 'Comercio al por mayor de productos farmacéuticos']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4647', 'description' => 'Comercio al por mayor de muebles, alfombras y aparatos de iluminación']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4648', 'description' => 'Comercio al por mayor de artículos de relojería y joyería']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4649', 'description' => 'Comercio al por mayor de otros artículos de uso doméstico']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4651', 'description' => 'Comercio al por mayor de ordenadores, equipos periféricos y programas informáticos']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4652', 'description' => 'Comercio al por mayor de equipos electrónicos y de telecomunicaciones y sus componentes']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4661', 'description' => 'Comercio al por mayor de maquinaria, equipos y suministros agrícolas']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4662', 'description' => 'Comercio al por mayor de máquinas herramienta']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4663', 'description' => 'Comercio al por mayor de maquinaria para la minería, la construcción y la ingeniería civil']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4664', 'description' => 'Comercio al por mayor de maquinaria para la industria textil y de máquinas de coser y tricotar']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4665', 'description' => 'Comercio al por mayor de muebles de oficina']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4666', 'description' => 'Comercio al por mayor de otra maquinaria y equipo de oficina']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4669', 'description' => 'Comercio al por mayor de otra maquinaria y equipo']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4671', 'description' => 'Comercio al por mayor de combustibles sólidos, líquidos y gaseosos, y productos similares']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4672', 'description' => 'Comercio al por mayor de metales y minerales metálicos']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4673', 'description' => 'Comercio al por mayor de madera, materiales de construcción y aparatos sanitarios']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4674', 'description' => 'Comercio al por mayor de ferretería, fontanería y calefacción']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4675', 'description' => 'Comercio al por mayor de productos químicos']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4676', 'description' => 'Comercio al por mayor de otros productos semielaborados']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4677', 'description' => 'Comercio al por mayor de chatarra y productos de desecho']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4690', 'description' => 'Comercio al por mayor no especializado']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4711', 'description' => 'Comercio al por menor en establecimientos no especializados, con predominio en productos alimenticios, bebidas y tabaco']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4719', 'description' => 'Otro comercio al por menor en establecimientos no especializados']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4721', 'description' => 'Comercio al por menor de frutas y hortalizas en establecimientos especializados']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4722', 'description' => 'Comercio al por menor de carne y productos cárnicos en establecimientos especializados']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4723', 'description' => 'Comercio al por menor de pescados y mariscos en establecimientos especializados']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4724', 'description' => 'Comercio al por menor de pan y productos de panadería, confitería y pastelería en establecimientos especializados']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4725', 'description' => 'Comercio al por menor de bebidas en establecimientos especializados']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4726', 'description' => 'Comercio al por menor de productos de tabaco en establecimientos especializados']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4729', 'description' => 'Otro comercio al por menor de productos alimenticios en establecimientos especializados']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4730', 'description' => 'Comercio al por menor de combustible para la automoción en establecimientos especializados']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4741', 'description' => 'Comercio al por menor de ordenadores, equipos periféricos y programas informáticos en establecimientos especializados']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4742', 'description' => 'Comercio al por menor de equipos de telecomunicaciones en establecimientos especializados']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4743', 'description' => 'Comercio al por menor de equipos de audio y vídeo en establecimientos especializados']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4751', 'description' => 'Comercio al por menor de textiles en establecimientos especializados']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4752', 'description' => 'Comercio al por menor de ferretería, pintura y vidrio en establecimientos especializados']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4753', 'description' => 'Comercio al por menor de alfombras, moquetas y revestimientos de paredes y suelos en establecimientos especializados']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4754', 'description' => 'Comercio al por menor de aparatos electrodomésticos en establecimientos especializados']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4759', 'description' => 'Comercio al por menor de muebles, aparatos de iluminación y otros artículos de uso doméstico en establecimientos especializados']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4761', 'description' => 'Comercio al por menor de libros en establecimientos especializados']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4762', 'description' => 'Comercio al por menor de periódicos y artículos de papelería en establecimientos especializados']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4763', 'description' => 'Comercio al por menor de grabaciones de música y vídeo en establecimientos especializados']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4764', 'description' => 'Comercio al por menor de artículos deportivos en establecimientos especializados']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4765', 'description' => 'Comercio al por menor de juegos y juguetes en establecimientos especializados']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4771', 'description' => 'Comercio al por menor de prendas de vestir en establecimientos especializados']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4772', 'description' => 'Comercio al por menor de calzado y artículos de cuero en establecimientos especializados']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4773', 'description' => 'Comercio al por menor de productos farmacéuticos en establecimientos especializados']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4774', 'description' => 'Comercio al por menor de artículos médicos y ortopédicos en establecimientos especializados']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4775', 'description' => 'Comercio al por menor de productos cosméticos e higiénicos en establecimientos especializados']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4776', 'description' => 'Comercio al por menor de flores, plantas, semillas, fertilizantes, animales de compañía y alimentos para los mismos en establecimientos especializados']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4777', 'description' => 'Comercio al por menor de artículos de relojería y joyería en establecimientos especializados']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4778', 'description' => 'Otro comercio al por menor de artículos nuevos en establecimientos especializados']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4779', 'description' => 'Comercio al por menor de artículos de segunda mano en establecimientos']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4781', 'description' => 'Comercio al por menor de productos alimenticios, bebidas y tabaco en puestos de venta y en mercadillos']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4782', 'description' => 'Comercio al por menor de productos textiles, prendas de vestir y calzado en puestos de venta y en mercadillos']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4789', 'description' => 'Comercio al por menor de otros productos en puestos de venta y en mercadillos']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4791', 'description' => 'Comercio al por menor por correspondencia o Internet']);
        BusinessArea::create(['area_group_id' => '7', 'area_code' => '4799', 'description' => 'Otro comercio al por menor no realizado ni en establecimientos, ni en puestos de venta ni en mercadillos']);
        /* 8 */
        BusinessArea::create(['area_group_id' => '8', 'area_code' => '4910', 'description' => 'Transporte interurbano de pasajeros por ferrocarril']);
        BusinessArea::create(['area_group_id' => '8', 'area_code' => '4920', 'description' => 'Transporte de mercancías por ferrocarril']);
        BusinessArea::create(['area_group_id' => '8', 'area_code' => '4931', 'description' => 'Transporte terrestre urbano y suburbano de pasajeros']);
        BusinessArea::create(['area_group_id' => '8', 'area_code' => '4932', 'description' => 'Transporte por taxi']);
        BusinessArea::create(['area_group_id' => '8', 'area_code' => '4939', 'description' => 'tipos de transporte terrestre de pasajeros n.c.o.p.']);
        BusinessArea::create(['area_group_id' => '8', 'area_code' => '4941', 'description' => 'Transporte de mercancías por carretera']);
        BusinessArea::create(['area_group_id' => '8', 'area_code' => '4942', 'description' => 'Servicios de mudanza']);
        BusinessArea::create(['area_group_id' => '8', 'area_code' => '4950', 'description' => 'Transporte por tubería']);
        BusinessArea::create(['area_group_id' => '8', 'area_code' => '5010', 'description' => 'Transporte marítimo de pasajeros']);
        BusinessArea::create(['area_group_id' => '8', 'area_code' => '5020', 'description' => 'Transporte marítimo de mercancías']);
        BusinessArea::create(['area_group_id' => '8', 'area_code' => '5030', 'description' => 'Transporte de pasajeros por vías navegables interiores']);
        BusinessArea::create(['area_group_id' => '8', 'area_code' => '5040', 'description' => 'Transporte de mercancías por vías navegables interiores']);
        BusinessArea::create(['area_group_id' => '8', 'area_code' => '5110', 'description' => 'Transporte aéreo de pasajeros']);
        BusinessArea::create(['area_group_id' => '8', 'area_code' => '5121', 'description' => 'Transporte aéreo de mercancías']);
        BusinessArea::create(['area_group_id' => '8', 'area_code' => '5122', 'description' => 'Transporte espacial']);
        BusinessArea::create(['area_group_id' => '8', 'area_code' => '5210', 'description' => 'Depósito y almacenamiento']);
        BusinessArea::create(['area_group_id' => '8', 'area_code' => '5221', 'description' => 'Actividades anexas al transporte terrestre']);
        BusinessArea::create(['area_group_id' => '8', 'area_code' => '5222', 'description' => 'Actividades anexas al transporte marítimo y por vías navegables interiores']);
        BusinessArea::create(['area_group_id' => '8', 'area_code' => '5223', 'description' => 'Actividades anexas al transporte aéreo']);
        BusinessArea::create(['area_group_id' => '8', 'area_code' => '5224', 'description' => 'Manipulación de mercancías']);
        BusinessArea::create(['area_group_id' => '8', 'area_code' => '5229', 'description' => 'Otras actividades anexas al transporte']);
        BusinessArea::create(['area_group_id' => '8', 'area_code' => '5310', 'description' => 'Actividades postales sometidas a la obligación del servicio universal']);
        BusinessArea::create(['area_group_id' => '8', 'area_code' => '5320', 'description' => 'Otras actividades postales y de correos']);
        /* 9 */
        BusinessArea::create(['area_group_id' => '9', 'area_code' => '5510', 'description' => 'Hoteles y alojamientos similares']);
        BusinessArea::create(['area_group_id' => '9', 'area_code' => '5520', 'description' => 'Alojamientos turísticos y otros alojamientos de corta estancia']);
        BusinessArea::create(['area_group_id' => '9', 'area_code' => '5530', 'description' => 'Campings y aparcamientos para caravanas']);
        BusinessArea::create(['area_group_id' => '9', 'area_code' => '5590', 'description' => 'Otros alojamientos']);
        BusinessArea::create(['area_group_id' => '9', 'area_code' => '5610', 'description' => 'Restaurantes y puestos de comidas']);
        BusinessArea::create(['area_group_id' => '9', 'area_code' => '5621', 'description' => 'Provisión de comidas preparadas para eventos']);
        BusinessArea::create(['area_group_id' => '9', 'area_code' => '5629', 'description' => 'Otros servicios de comidas']);
        BusinessArea::create(['area_group_id' => '9', 'area_code' => '5630', 'description' => 'Establecimientos de bebidas']);
        /* 10 */
        BusinessArea::create(['area_group_id' => '10', 'area_code' => '5811', 'description' => 'Edición de libros']);
        BusinessArea::create(['area_group_id' => '10', 'area_code' => '5812', 'description' => 'Edición de directorios y guías de direcciones postales']);
        BusinessArea::create(['area_group_id' => '10', 'area_code' => '5813', 'description' => 'Edición de periódicos']);
        BusinessArea::create(['area_group_id' => '10', 'area_code' => '5814', 'description' => 'Edición de revistas']);
        BusinessArea::create(['area_group_id' => '10', 'area_code' => '5819', 'description' => 'Otras actividades editoriales']);
        BusinessArea::create(['area_group_id' => '10', 'area_code' => '5821', 'description' => 'Edición de videojuegos']);
        BusinessArea::create(['area_group_id' => '10', 'area_code' => '5829', 'description' => 'Edición de otros programas informáticos']);
        BusinessArea::create(['area_group_id' => '10', 'area_code' => '5912', 'description' => 'Actividades de postproducción cinematográfica, de vídeo y de programas de televisión']);
        BusinessArea::create(['area_group_id' => '10', 'area_code' => '5914', 'description' => 'Actividades de exhibición cinematográfica']);
        BusinessArea::create(['area_group_id' => '10', 'area_code' => '5915', 'description' => 'Actividades de producción cinematográfica y de vídeo']);
        BusinessArea::create(['area_group_id' => '10', 'area_code' => '5916', 'description' => 'Actividades de producciones de programas de televisión']);
        BusinessArea::create(['area_group_id' => '10', 'area_code' => '5917', 'description' => 'Actividades de distribución cinematográfica y de vídeo']);
        BusinessArea::create(['area_group_id' => '10', 'area_code' => '5918', 'description' => 'Actividades de distribución de programas de televisión']);
        BusinessArea::create(['area_group_id' => '10', 'area_code' => '5920', 'description' => 'Actividades de grabación de sonido y edición musical']);
        BusinessArea::create(['area_group_id' => '10', 'area_code' => '6010', 'description' => 'Actividades de radiodifusión']);
        BusinessArea::create(['area_group_id' => '10', 'area_code' => '6020', 'description' => 'Actividades de programación y emisión de televisión']);
        BusinessArea::create(['area_group_id' => '10', 'area_code' => '6110', 'description' => 'Telecomunicaciones por cable']);
        BusinessArea::create(['area_group_id' => '10', 'area_code' => '6120', 'description' => 'Telecomunicaciones inalámbricas']);
        BusinessArea::create(['area_group_id' => '10', 'area_code' => '6130', 'description' => 'Telecomunicaciones por satélite']);
        BusinessArea::create(['area_group_id' => '10', 'area_code' => '6190', 'description' => 'Otras actividades de telecomunicaciones']);
        BusinessArea::create(['area_group_id' => '10', 'area_code' => '6201', 'description' => 'Actividades de programación informática']);
        BusinessArea::create(['area_group_id' => '10', 'area_code' => '6202', 'description' => 'Actividades de consultoría informática']);
        BusinessArea::create(['area_group_id' => '10', 'area_code' => '6203', 'description' => 'Gestión de recursos informáticos']);
        BusinessArea::create(['area_group_id' => '10', 'area_code' => '6209', 'description' => 'Otros servicios relacionados con las tecnologías de la información y la informática']);
        BusinessArea::create(['area_group_id' => '10', 'area_code' => '6311', 'description' => 'Proceso de datos, hosting y actividades relacionadas']);
        BusinessArea::create(['area_group_id' => '10', 'area_code' => '6312', 'description' => 'Portales web']);
        BusinessArea::create(['area_group_id' => '10', 'area_code' => '6391', 'description' => 'Actividades de las agencias de noticias']);
        BusinessArea::create(['area_group_id' => '10', 'area_code' => '6399', 'description' => 'Otros servicios de información n.c.o.p.']);
        /* 11 */
        BusinessArea::create(['area_group_id' => '11', 'area_code' => '6411', 'description' => 'Banco central']);
        BusinessArea::create(['area_group_id' => '11', 'area_code' => '6419', 'description' => 'Otra intermediación monetaria']);
        BusinessArea::create(['area_group_id' => '11', 'area_code' => '6420', 'description' => 'Actividades de las sociedades holding']);
        BusinessArea::create(['area_group_id' => '11', 'area_code' => '6430', 'description' => 'Inversión colectiva, fondos y entidades financieras similares']);
        BusinessArea::create(['area_group_id' => '11', 'area_code' => '6491', 'description' => 'Arrendamiento financiero']);
        BusinessArea::create(['area_group_id' => '11', 'area_code' => '6492', 'description' => 'Otras actividades crediticias']);
        BusinessArea::create(['area_group_id' => '11', 'area_code' => '6499', 'description' => 'Otros servicios financieros, excepto seguros y fondos de pensiones n.c.o.p.']);
        BusinessArea::create(['area_group_id' => '11', 'area_code' => '6511', 'description' => 'Seguros de vida']);
        BusinessArea::create(['area_group_id' => '11', 'area_code' => '6512', 'description' => 'Seguros distintos de los seguros de vida']);
        BusinessArea::create(['area_group_id' => '11', 'area_code' => '6520', 'description' => 'Reaseguros']);
        BusinessArea::create(['area_group_id' => '11', 'area_code' => '6530', 'description' => 'Fondos de pensiones']);
        BusinessArea::create(['area_group_id' => '11', 'area_code' => '6611', 'description' => 'Administración de mercados financieros']);
        BusinessArea::create(['area_group_id' => '11', 'area_code' => '6612', 'description' => 'Actividades de intermediación en operaciones con valores y otros activos']);
        BusinessArea::create(['area_group_id' => '11', 'area_code' => '6619', 'description' => 'Otras actividades auxiliares a los servicios financieros, excepto seguros y fondos de pensiones']);
        BusinessArea::create(['area_group_id' => '11', 'area_code' => '6621', 'description' => 'Evaluación de riesgos y daños']);
        BusinessArea::create(['area_group_id' => '11', 'area_code' => '6622', 'description' => 'Actividades de agentes y corredores de seguros']);
        BusinessArea::create(['area_group_id' => '11', 'area_code' => '6629', 'description' => 'Otras actividades auxiliares a seguros y fondos de pensiones']);
        BusinessArea::create(['area_group_id' => '11', 'area_code' => '6630', 'description' => 'Actividades de gestión de fondos']);
        /* 12 */
        BusinessArea::create(['area_group_id' => '12', 'area_code' => '6810', 'description' => 'Compraventa de bienes inmobiliarios por cuenta propia']);
        BusinessArea::create(['area_group_id' => '12', 'area_code' => '6820', 'description' => 'Alquiler de bienes inmobiliarios por cuenta propia']);
        BusinessArea::create(['area_group_id' => '12', 'area_code' => '6831', 'description' => 'Agentes de la propiedad inmobiliaria']);
        BusinessArea::create(['area_group_id' => '12', 'area_code' => '6832', 'description' => 'Gestión y administración de la propiedad inmobiliaria']);
        /* 13 */
        BusinessArea::create(['area_group_id' => '13', 'area_code' => '6910', 'description' => 'Actividades jurídicas']);
        BusinessArea::create(['area_group_id' => '13', 'area_code' => '6920', 'description' => 'Actividades de contabilidad, teneduría de libros, auditoría y asesoría fiscal']);
        BusinessArea::create(['area_group_id' => '13', 'area_code' => '7010', 'description' => 'Actividades de las sedes centrales']);
        BusinessArea::create(['area_group_id' => '13', 'area_code' => '7021', 'description' => 'Relaciones públicas y comunicación']);
        BusinessArea::create(['area_group_id' => '13', 'area_code' => '7022', 'description' => 'Otras actividades de consultoría de gestión empresarial']);
        BusinessArea::create(['area_group_id' => '13', 'area_code' => '7111', 'description' => 'Servicios técnicos de arquitectura']);
        BusinessArea::create(['area_group_id' => '13', 'area_code' => '7112', 'description' => 'Servicios técnicos de ingeniería y otras actividades relacionadas con el asesoramiento técnico']);
        BusinessArea::create(['area_group_id' => '13', 'area_code' => '7120', 'description' => 'Ensayos y análisis técnicos']);
        BusinessArea::create(['area_group_id' => '13', 'area_code' => '7211', 'description' => 'Investigación y desarrollo experimental en biotecnología']);
        BusinessArea::create(['area_group_id' => '13', 'area_code' => '7219', 'description' => 'Otra investigación y desarrollo experimental en ciencias naturales y técnicas']);
        BusinessArea::create(['area_group_id' => '13', 'area_code' => '7220', 'description' => 'Investigación y desarrollo experimental en ciencias sociales y humanidades']);
        BusinessArea::create(['area_group_id' => '13', 'area_code' => '7311', 'description' => 'Agencias de publicidad']);
        BusinessArea::create(['area_group_id' => '13', 'area_code' => '7312', 'description' => 'Servicios de representación de medios de comunicación']);
        BusinessArea::create(['area_group_id' => '13', 'area_code' => '7320', 'description' => 'Estudio de mercado y realización de encuestas de opinión pública']);
        BusinessArea::create(['area_group_id' => '13', 'area_code' => '7410', 'description' => 'Actividades de diseño especializado']);
        BusinessArea::create(['area_group_id' => '13', 'area_code' => '7420', 'description' => 'Actividades de fotografía']);
        BusinessArea::create(['area_group_id' => '13', 'area_code' => '7430', 'description' => 'Actividades de traducción e interpretación']);
        BusinessArea::create(['area_group_id' => '13', 'area_code' => '7490', 'description' => 'Otras actividades profesionales, científicas y técnicas n.c.o.p.']);
        BusinessArea::create(['area_group_id' => '13', 'area_code' => '7500', 'description' => 'Actividades veterinarias']);
        /* 14 */
        BusinessArea::create(['area_group_id' => '14', 'area_code' => '7711', 'description' => 'Alquiler de automóviles y vehículos de motor ligeros']);
        BusinessArea::create(['area_group_id' => '14', 'area_code' => '7712', 'description' => 'Alquiler de camiones']);
        BusinessArea::create(['area_group_id' => '14', 'area_code' => '7721', 'description' => 'Alquiler de artículos de ocio y deportivos']);
        BusinessArea::create(['area_group_id' => '14', 'area_code' => '7722', 'description' => 'Alquiler de cintas de vídeo y discos']);
        BusinessArea::create(['area_group_id' => '14', 'area_code' => '7729', 'description' => 'Alquiler de otros efectos personales y artículos de uso doméstico']);
        BusinessArea::create(['area_group_id' => '14', 'area_code' => '7731', 'description' => 'Alquiler de maquinaria y equipo de uso agrícola']);
        BusinessArea::create(['area_group_id' => '14', 'area_code' => '7732', 'description' => 'Alquiler de maquinaria y equipo para la construcción e ingeniería civil']);
        BusinessArea::create(['area_group_id' => '14', 'area_code' => '7733', 'description' => 'Alquiler de maquinaria y equipo de oficina, incluidos ordenadores']);
        BusinessArea::create(['area_group_id' => '14', 'area_code' => '7734', 'description' => 'Alquiler de medios de navegación']);
        BusinessArea::create(['area_group_id' => '14', 'area_code' => '7735', 'description' => 'Alquiler de medios de transporte aéreo']);
        BusinessArea::create(['area_group_id' => '14', 'area_code' => '7739', 'description' => 'Alquiler de otra maquinaria, equipos y bienes tangibles n.c.o.p.']);
        BusinessArea::create(['area_group_id' => '14', 'area_code' => '7740', 'description' => 'Arrendamiento de la propiedad intelectual y productos similares, excepto trabajos protegidos por los derechos de autor']);
        BusinessArea::create(['area_group_id' => '14', 'area_code' => '7810', 'description' => 'Actividades de las agencias de colocación']);
        BusinessArea::create(['area_group_id' => '14', 'area_code' => '7820', 'description' => 'Actividades de las empresas de trabajo temporal']);
        BusinessArea::create(['area_group_id' => '14', 'area_code' => '7830', 'description' => 'Otra provisión de recursos humanos']);
        BusinessArea::create(['area_group_id' => '14', 'area_code' => '7911', 'description' => 'Actividades de las agencias de viajes']);
        BusinessArea::create(['area_group_id' => '14', 'area_code' => '7912', 'description' => 'Actividades de los operadores turísticos']);
        BusinessArea::create(['area_group_id' => '14', 'area_code' => '7990', 'description' => 'Otros servicios de reservas y actividades relacionadas con los mismos']);
        BusinessArea::create(['area_group_id' => '14', 'area_code' => '8010', 'description' => 'Actividades de seguridad privada']);
        BusinessArea::create(['area_group_id' => '14', 'area_code' => '8020', 'description' => 'Servicios de sistemas de seguridad']);
        BusinessArea::create(['area_group_id' => '14', 'area_code' => '8030', 'description' => 'Actividades de investigación']);
        BusinessArea::create(['area_group_id' => '14', 'area_code' => '8110', 'description' => 'Servicios integrales a edificios e instalaciones']);
        BusinessArea::create(['area_group_id' => '14', 'area_code' => '8121', 'description' => 'Limpieza general de edificios']);
        BusinessArea::create(['area_group_id' => '14', 'area_code' => '8122', 'description' => 'Otras actividades de limpieza industrial y de edificios']);
        BusinessArea::create(['area_group_id' => '14', 'area_code' => '8129', 'description' => 'Otras actividades de limpieza']);
        BusinessArea::create(['area_group_id' => '14', 'area_code' => '8130', 'description' => 'Actividades de jardinería']);
        BusinessArea::create(['area_group_id' => '14', 'area_code' => '8211', 'description' => 'Servicios administrativos combinados']);
        BusinessArea::create(['area_group_id' => '14', 'area_code' => '8219', 'description' => 'Actividades de fotocopiado, preparación de documentos y otras actividades especializadas de oficina']);
        BusinessArea::create(['area_group_id' => '14', 'area_code' => '8220', 'description' => 'Actividades de los centros de llamadas']);
        BusinessArea::create(['area_group_id' => '14', 'area_code' => '8230', 'description' => 'Organización de convenciones y ferias de muestras']);
        BusinessArea::create(['area_group_id' => '14', 'area_code' => '8291', 'description' => 'Actividades de las agencias de cobros y de información comercial']);
        BusinessArea::create(['area_group_id' => '14', 'area_code' => '8292', 'description' => 'Actividades de envasado y empaquetado']);
        BusinessArea::create(['area_group_id' => '14', 'area_code' => '8299', 'description' => 'Otras actividades de apoyo a las empresas n.c.o.p.']);
        /* 15 */
        BusinessArea::create(['area_group_id' => '15', 'area_code' => '8411', 'description' => 'Actividades generales de la Administración Pública']);
        BusinessArea::create(['area_group_id' => '15', 'area_code' => '8412', 'description' => 'Regulación de las actividades sanitarias, educativas y culturales y otros servicios sociales, excepto Seguridad Social']);
        BusinessArea::create(['area_group_id' => '15', 'area_code' => '8413', 'description' => 'Regulación de la actividad económica y contribución a su mayor eficiencia']);
        BusinessArea::create(['area_group_id' => '15', 'area_code' => '8421', 'description' => 'Asuntos exteriores']);
        BusinessArea::create(['area_group_id' => '15', 'area_code' => '8422', 'description' => 'Defensa']);
        BusinessArea::create(['area_group_id' => '15', 'area_code' => '8423', 'description' => 'Justicia']);
        BusinessArea::create(['area_group_id' => '15', 'area_code' => '8424', 'description' => 'Orden público y seguridad']);
        BusinessArea::create(['area_group_id' => '15', 'area_code' => '8425', 'description' => 'Protección civil']);
        BusinessArea::create(['area_group_id' => '15', 'area_code' => '8430', 'description' => 'Seguridad Social obligatoria']);
        /* 16 */
        BusinessArea::create(['area_group_id' => '16', 'area_code' => '8510', 'description' => 'Educación preprimaria']);
        BusinessArea::create(['area_group_id' => '16', 'area_code' => '8520', 'description' => 'Educación primaria']);
        BusinessArea::create(['area_group_id' => '16', 'area_code' => '8531', 'description' => 'Educación secundaria general']);
        BusinessArea::create(['area_group_id' => '16', 'area_code' => '8532', 'description' => 'Educación secundaria técnica y profesional']);
        BusinessArea::create(['area_group_id' => '16', 'area_code' => '8541', 'description' => 'Educación postsecundaria no terciaria']);
        BusinessArea::create(['area_group_id' => '16', 'area_code' => '8543', 'description' => 'Educación universitaria']);
        BusinessArea::create(['area_group_id' => '16', 'area_code' => '8544', 'description' => 'Educación terciaria no universitaria']);
        BusinessArea::create(['area_group_id' => '16', 'area_code' => '8551', 'description' => 'Educación deportiva y recreativa']);
        BusinessArea::create(['area_group_id' => '16', 'area_code' => '8552', 'description' => 'Educación cultural']);
        BusinessArea::create(['area_group_id' => '16', 'area_code' => '8553', 'description' => 'Actividades de las escuelas de conducción y pilotaje']);
        BusinessArea::create(['area_group_id' => '16', 'area_code' => '8559', 'description' => 'Otra educación n.c.o.p.']);
        BusinessArea::create(['area_group_id' => '16', 'area_code' => '8560', 'description' => 'Actividades auxiliares a la educación']);
        /* 17 */
        BusinessArea::create(['area_group_id' => '17', 'area_code' => '8610', 'description' => 'Actividades hospitalarias']);
        BusinessArea::create(['area_group_id' => '17', 'area_code' => '8621', 'description' => 'Actividades de medicina general']);
        BusinessArea::create(['area_group_id' => '17', 'area_code' => '8622', 'description' => 'Actividades de medicina especializada']);
        BusinessArea::create(['area_group_id' => '17', 'area_code' => '8623', 'description' => 'Actividades odontológicas']);
        BusinessArea::create(['area_group_id' => '17', 'area_code' => '8690', 'description' => 'Otras actividades sanitarias']);
        BusinessArea::create(['area_group_id' => '17', 'area_code' => '8710', 'description' => 'Asistencia en establecimientos residenciales con cuidados sanitarios']);
        BusinessArea::create(['area_group_id' => '17', 'area_code' => '8720', 'description' => 'Asistencia en establecimientos residenciales para personas con discapacidad intelectual, enfermedad mental y drogodependencia']);
        BusinessArea::create(['area_group_id' => '17', 'area_code' => '8731', 'description' => 'Asistencia en establecimientos residenciales para personas mayores']);
        BusinessArea::create(['area_group_id' => '17', 'area_code' => '8732', 'description' => 'Asistencia en establecimientos residenciales para personas con discapacidad física']);
        BusinessArea::create(['area_group_id' => '17', 'area_code' => '8790', 'description' => 'Otras actividades de asistencia en establecimientos residenciales']);
        BusinessArea::create(['area_group_id' => '17', 'area_code' => '8811', 'description' => 'Actividades de servicios sociales sin alojamiento para personas mayores']);
        BusinessArea::create(['area_group_id' => '17', 'area_code' => '8812', 'description' => 'Actividades de servicios sociales sin alojamiento para personas con discapacidad']);
        BusinessArea::create(['area_group_id' => '17', 'area_code' => '8891', 'description' => 'Actividades de cuidado diurno de niños']);
        BusinessArea::create(['area_group_id' => '17', 'area_code' => '8899', 'description' => 'Otros actividades de servicios sociales sin alojamiento n.c.o.p.']);
        /* 18 */
        BusinessArea::create(['area_group_id' => '18', 'area_code' => '9001', 'description' => 'Artes escénicas']);
        BusinessArea::create(['area_group_id' => '18', 'area_code' => '9002', 'description' => 'Actividades auxiliares a las artes escénicas']);
        BusinessArea::create(['area_group_id' => '18', 'area_code' => '9003', 'description' => 'Creación artística y literaria']);
        BusinessArea::create(['area_group_id' => '18', 'area_code' => '9004', 'description' => 'Gestión de salas de espectáculos']);
        BusinessArea::create(['area_group_id' => '18', 'area_code' => '9102', 'description' => 'Actividades de museos']);
        BusinessArea::create(['area_group_id' => '18', 'area_code' => '9103', 'description' => 'Gestión de lugares y edificios históricos']);
        BusinessArea::create(['area_group_id' => '18', 'area_code' => '9104', 'description' => 'Actividades de los jardines botánicos, parques zoológicos y reservas naturales']);
        BusinessArea::create(['area_group_id' => '18', 'area_code' => '9105', 'description' => 'Actividades de bibliotecas']);
        BusinessArea::create(['area_group_id' => '18', 'area_code' => '9106', 'description' => 'Actividades de archivos']);
        BusinessArea::create(['area_group_id' => '18', 'area_code' => '9200', 'description' => 'Actividades de juegos de azar y apuestas']);
        BusinessArea::create(['area_group_id' => '18', 'area_code' => '9311', 'description' => 'Gestión de instalaciones deportivas']);
        BusinessArea::create(['area_group_id' => '18', 'area_code' => '9312', 'description' => 'Actividades de los clubes deportivos']);
        BusinessArea::create(['area_group_id' => '18', 'area_code' => '9313', 'description' => 'Actividades de los gimnasios']);
        BusinessArea::create(['area_group_id' => '18', 'area_code' => '9319', 'description' => 'Otras actividades deportivas']);
        BusinessArea::create(['area_group_id' => '18', 'area_code' => '9321', 'description' => 'Actividades de los parques de atracciones y los parques temáticos']);
        BusinessArea::create(['area_group_id' => '18', 'area_code' => '9329', 'description' => 'Otras actividades recreativas y de entretenimiento']);
        /* 19 */
        BusinessArea::create(['area_group_id' => '19', 'area_code' => '9411', 'description' => 'Actividades de organizaciones empresariales y patronales']);
        BusinessArea::create(['area_group_id' => '19', 'area_code' => '9412', 'description' => 'Actividades de organizaciones profesionales']);
        BusinessArea::create(['area_group_id' => '19', 'area_code' => '9420', 'description' => 'Actividades sindicales']);
        BusinessArea::create(['area_group_id' => '19', 'area_code' => '9491', 'description' => 'Actividades de organizaciones religiosas']);
        BusinessArea::create(['area_group_id' => '19', 'area_code' => '9492', 'description' => 'Actividades de organizaciones políticas']);
        BusinessArea::create(['area_group_id' => '19', 'area_code' => '9499', 'description' => 'Otras actividades asociativas n.c.o.p.']);
        BusinessArea::create(['area_group_id' => '19', 'area_code' => '9511', 'description' => 'Reparación de ordenadores y equipos periféricos']);
        BusinessArea::create(['area_group_id' => '19', 'area_code' => '9512', 'description' => 'Reparación de equipos de comunicación']);
        BusinessArea::create(['area_group_id' => '19', 'area_code' => '9521', 'description' => 'Reparación de aparatos electrónicos de audio y vídeo de uso doméstico']);
        BusinessArea::create(['area_group_id' => '19', 'area_code' => '9522', 'description' => 'Reparación de aparatos electrodomésticos y de equipos para el hogar y el jardín']);
        BusinessArea::create(['area_group_id' => '19', 'area_code' => '9523', 'description' => 'Reparación de calzado y artículos de cuero']);
        BusinessArea::create(['area_group_id' => '19', 'area_code' => '9524', 'description' => 'Reparación de muebles y artículos de menaje']);
        BusinessArea::create(['area_group_id' => '19', 'area_code' => '9525', 'description' => 'Reparación de relojes y joyería']);
        BusinessArea::create(['area_group_id' => '19', 'area_code' => '9529', 'description' => 'Reparación de otros efectos personales y artículos de uso doméstico']);
        BusinessArea::create(['area_group_id' => '19', 'area_code' => '9601', 'description' => 'Lavado y limpieza de prendas textiles y de piel']);
        BusinessArea::create(['area_group_id' => '19', 'area_code' => '9602', 'description' => 'Peluquería y otros tratamientos de belleza']);
        BusinessArea::create(['area_group_id' => '19', 'area_code' => '9603', 'description' => 'Pompas fúnebres y actividades relacionadas']);
        BusinessArea::create(['area_group_id' => '19', 'area_code' => '9604', 'description' => 'Actividades de mantenimiento físico']);
        BusinessArea::create(['area_group_id' => '19', 'area_code' => '9609', 'description' => 'Otras servicios personales n.c.o.p.']);
        /* 20 */
        BusinessArea::create(['area_group_id' => '20', 'area_code' => '9700', 'description' => 'Actividades de los hogares como empleadores de personal doméstico']);
        BusinessArea::create(['area_group_id' => '20', 'area_code' => '9810', 'description' => 'Actividades de los hogares como productores de bienes para uso propio']);
        BusinessArea::create(['area_group_id' => '20', 'area_code' => '9820', 'description' => 'Actividades de los hogares como productores de servicios para uso propio']);
        /* 21 */
        BusinessArea::create(['area_group_id' => '21', 'area_code' => '9900', 'description' => 'Actividades de organizaciones y organismos extraterritoriales']);
    }
}
